---
language: node_js
node_js:
  - "4"
  - "6"
  - "8"

sudo: false

cache:
  yarn: true

matrix:
  fast_finish: true

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - node --version
  - yarn install --no-lockfile

script:
  # https://github.com/jest-community/jest-runner-eslint/pull/15
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then
      yarn jest --coverage;
    else
      yarn test --coverage;
    fi

after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then
      ./upload-coverage.sh;
    fi
