---
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

sudo: false

cache:
  yarn: true

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - node --version
  - yarn install --no-lockfile

script:
    yarn test --coverage;

after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then
      node_modules/.bin/codecov;
    fi
